[opener]
edit = [
  { run = 'nvim "$@"', block = true, for = "unix" },
]
open = [
  { run = 'xdg-open "$@"', desc = "Open", for = "linux" },
]
image = [
  { run = 'imv "$@"', orphan = true, for = "unix" },
]
video = [
  { run = 'vlc "$@"', orphan = true, for = "unix" },
]
pdf = [
  { run = 'zathura "$@"', orphan = true, for = "unix" },
]
epub = [
  { run = 'zathura "$@"', orphan = true, for = "unix" },
]

[open]
rules = [
  { mime = "text/*", use = "edit" },
  { mime = "image/*", use = "image" },
  { mime = "video/*", use = "video" },
  { mime = "application/pdf", use = "pdf" },
  { mime = "application/epub+zip", use = "epub" },
]
