# ~/.config/hypr/hyprland.conf
source = ~/.config/hypr/conf/programs.conf
source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/monitor.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/look.conf
source = ~/.config/hypr/conf/layouts.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/rules.conf
source = ~/.config/hypr/conf/animations/ani_limefrenzy.conf
source = ~/.config/hypr/conf/decoration.conf
